version: '3.1'
services:
  knostr:
    image: knostr:0.3
    links:
      - "db"
    ports:
      - 8080:8080
      - 8082:8082
    restart: unless-stopped
  db:
    container_name: knostr-postgres
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: knostr
      POSTGRES_USER: knostr
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
