micronaut:
  application:
    name: knostr
  metrics:
    enabled: true
  otel:
    enabled: false

endpoints:
  all:
    port: 8082
    sensitive: false

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/knostr
    username: knostr
    password: root
    driver-class-name: org.postgresql.Driver
    dialect: POSTGRES
    db-type: postgres

jpa:
  default:
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logger:
  levels:
    io.micronaut.data.query: INFO

flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
